# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ValidateAndPlan
    displayName: Validate and Plan
    jobs:
      - job: ValidateAndPlan
        steps:
          - task: TerraformTaskV1@0
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: $(backendServiceAzureRM)
              backendAzureRmResourceGroupName: 'earth-azure-devops'
              backendAzureRmStorageAccountName: 'earthterraform'
              backendAzureRmContainerName: 'terraform'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV1@0
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTaskV1@0
            displayName: Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out=tfplan -input=false'
              environmentServiceNameAzureRM: $(backendServiceAzureRM)
          - publish: ./
            artifact: 'terraform-archive'
            displayName: Publish Terraform archive
  - stage: Apply
    displayName: Apply
    jobs:
      - deployment: HostedVs2017
        environment: tryit-aks-datadog
      - job: Apply
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            displayName: Download Terraform archive
            inputs:
              artifactName: 'terraform-archive'
              path: $(Build.SourcesDirectory)
          - task: Bash@3
            displayName: Grant read permission to terraform files
            inputs:
              targetType: 'inline'
              script: 'chmod -R 755 /home/vsts/work/1/s/.terraform/plugins/linux_amd64'
          - task: TerraformTaskV1@0
            displayName: Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: $(backendServiceAzureRM)
