# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ValidateAndPlan
    displayName: Validate and Plan
    jobs:
      - job: ValidateAndPlan
        steps:
          - task: TerraformTaskV1@0
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: $(backendServiceAzureRM)
              backendAzureRmResourceGroupName: 'earth-azure-devops'
              backendAzureRmStorageAccountName: 'earthterraform'
              backendAzureRmContainerName: 'terraform'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV1@0
            displayName: Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
          - task: TerraformTaskV1@0
            displayName: Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out=tfplan -input=false'
              environmentServiceNameAzureRM: $(backendServiceAzureRM)
